CREATE DATABASE IF NOT EXISTS sword;

USE sword;
CREATE TABLE IF NOT EXISTS users(
    login VARCHAR(30) PRIMARY KEY NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullName VARCHAR(50),
    emailUser VARCHAR(50) NOT NULL,
    isAdmin BOOLEAN DEFAULT FALSE
);
